config/routes.rb
Rails.application.routes.draw do

  resources :dinners
  resources :recipes
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinner.rb
class Dinner < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dinners_controller.rb
class DinnersController < ApplicationController
  before_action :set_dinner, only: [:show, :edit, :update, :destroy]

  # GET /dinners
  # GET /dinners.json
  def index
    @dinners = Dinner.all
  end

  # GET /dinners/1
  # GET /dinners/1.json
  def show
  end

  # GET /dinners/new
  def new
    @dinner = Dinner.new
  end

  # GET /dinners/1/edit
  def edit
  end

  # POST /dinners
  # POST /dinners.json
  def create
    @dinner = Dinner.new(dinner_params)

    respond_to do |format|
      if @dinner.save
        format.html { redirect_to @dinner, notice: 'Dinner was successfully created.' }
        format.json { render :show, status: :created, location: @dinner }
      else
        format.html { render :new }
        format.json { render json: @dinner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dinners/1
  # PATCH/PUT /dinners/1.json
  def update
    respond_to do |format|
      if @dinner.update(dinner_params)
        format.html { redirect_to @dinner, notice: 'Dinner was successfully updated.' }
        format.json { render :show, status: :ok, location: @dinner }
      else
        format.html { render :edit }
        format.json { render json: @dinner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dinners/1
  # DELETE /dinners/1.json
  def destroy
    @dinner.destroy
    respond_to do |format|
      format.html { redirect_to dinners_url, notice: 'Dinner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dinner
      @dinner = Dinner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dinner_params
      params.require(:dinner).permit(:recipe, :start_time)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :body, :ingredients, :cuisine, :main)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @chicken = Recipe.where(main: "Chicken")
    @beef = Recipe.where(main: "Ground Beef")
    @pork = Recipe.where(main: "Pork")
    @other = Recipe.where.not(main: ["Chicken", "Ground Beef", "Pork"])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinners_helper.rb
module DinnersHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/dinners/_form.html.erb
<%= form_for(dinner) do |f| %>
  <% if dinner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dinner.errors.count, "error") %> prohibited this dinner from being saved:</h2>

      <ul>
      <% dinner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe %>
    <%= f.text_field :recipe %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dinners/edit.html.erb
<h1>Editing Dinner</h1>

<%= render 'form', dinner: @dinner %>

<%= link_to 'Show', @dinner %> |
<%= link_to 'Back', dinners_path %>

app/views/dinners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dinners</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dinners.each do |dinner| %>
      <tr>
        <td><%= dinner.recipe %></td>
        <td><%= dinner.start_time %></td>
        <td><%= link_to 'Show', dinner %></td>
        <td><%= link_to 'Edit', edit_dinner_path(dinner) %></td>
        <td><%= link_to 'Destroy', dinner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dinner', new_dinner_path %>

<h2>Menu Plan</h3>
<%= month_calendar events: @dinners do |date, dinners| %>
  <%= date %>
  <% dinners.each do |dinner| %>
    <div>
      <%= dinner.recipe %>
    </div>
  <% end %>
<% end %>

app/views/dinners/new.html.erb
<h1>New Dinner</h1>

<%= render 'form', dinner: @dinner %>

<%= link_to 'Back', dinners_path %>

app/views/dinners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @dinner.recipe %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @dinner.start_time %>
</p>

<%= link_to 'Edit', edit_dinner_path(@dinner) %> |
<%= link_to 'Back', dinners_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kitchen Helper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <ul class="nav nav-tabs">
          <li><%= link_to "Home", root_path %> </li>
          <li><%= link_to "Recipes", recipes_path %> </li>
          <li><%= link_to "Menu Plan", dinners_path %></li>
        </ul>
      </nav>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
  </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
   <% end %> <!-- end of errors loop -->
   <div class="form-group">
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Edit recipe title" %>
   </div>
   <div class="form-group">
     <%= f.label :main %>
     <%= f.text_field :main, class: 'form-control', placeholder: "Main ingredient" %>
   </div>
   <div class="form-group">
     <%= f.label :cuisine %>
     <%= f.text_field :cuisine, class: 'form-control', placeholder: "Edit cuisine" %>
   </div>
   <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Edit recipe instructions" %>
   </div>
   <div class="form-group">
     <%= f.label :ingredients %>
     <%= f.text_area :ingredients, rows: 8, class: 'form-control', placeholder: "Edit ingredients" %>
   </div>
  <div class="actions">
    <%= f.submit "Save Recipe", class: 'btn btn-success' %>
  </div>
<% end %> <!-- end of form  -->

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show Recipe', @recipe %> |
<%= link_to 'All Recipes', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th><th>Main Ingredient</th><th>Cuisine</th><th>Details</th><th>Edit</th><th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.main %></td>
        <td><%= recipe.cuisine %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Delete Recipe', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'All Recipes', recipes_path %>

app/views/recipes/show.html.erb
<h2><%= @recipe.title %></h2>
<h4>Main Ingredient</h4>
<p> <%= @recipe.main %></p>
<h4>Cooking Instructions</h4>
<p><%= @recipe.body %></p>
<h4>Ingredients</h4>
<p><%= @recipe.ingredients %></p>

<%= link_to 'Edit Recipe', edit_recipe_path(@recipe) %> |
<%= link_to 'All Recipes', recipes_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Kitchen Helper</h1>

<h3>Chicken Recipes</h3>
<% @chicken.each do |recipe| %>
  <p><%= link_to recipe.title, recipe %><p>
<% end %>

<h3>Ground Beef Recipes</h3>
<% @beef.each do |recipe| %>
  <p><%= link_to recipe.title, recipe %><p>
<% end %>

<h3>Pork Recipes</h3>
<% @pork.each do |recipe| %>
  <p><%= link_to recipe.title, recipe %><p>
<% end %>

<h3>Other Recipes</h3>
<% @other.each do |recipe| %>
  <p><%= link_to recipe.title, recipe %><p>
<% end %>